### PR TITLE
Developing

### PR DESCRIPTION
**Pull request by willwildred**
[DEMO LINK](https://willwildred.github.io/layout_creativeBakery/)
<br>
[design](https://www.figma.com/file/dY3izAm0Vspsmra4lQWQIP/Bakerlab-FE-students?node-id=0%3A1)

### CODE REVIEW

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
1. add favicon
2. add correct title

**Review by SanyaBratashchuk — CHANGES_REQUESTED** [review]
Check paddings on tablet/mobile dimensions 
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! Almost done! 
Screenshot 2024-02-25 at 14 47 45
Screenshot 2024-02-25 at 14 48 00

**Review by anastasiiavorobiova — APPROVED** [review]
Awesome!

**Pull request closed without merging**
