### PR TITLE
test

### PR DESCRIPTION
**Pull request by OleksandrFEdev**
[DEMO LINK](https://<OleksandrFEdev>.github.io/layout_creativeBakery/).

### CODE REVIEW

**Review by VitaliyBodnar — CHANGES_REQUESTED** [review]
- demo link is not valid 
Screenshot 2023-09-21 at 20 00 39

**Comment by OleksandrFEdev** [comment]
> [DEMO LINK](https:/OleksandrFEdev.github.io/layout_creativeBakery/).

**Review by etojeDenys — CHANGES_REQUESTED** [review]
you still have not fixed your demo link in the PR description(copy from readme.md)

**Comment by OleksandrFEdev** [comment]
[DEMO LINK](https://OleksandrFEdev.github.io/layout_creativeBakery/).

**Review by etojeDenys — CHANGES_REQUESTED** [review]
image
try to re-deploy your work or feel free to ask in chat

**Review by etojeDenys — CHANGES_REQUESTED** [review]
1. you should change the cookie color button hover
image



2. add some hovers to links
3. should be the links
image


4. Add a smooth scroll for the whole page (scroll-behavior: smooth;)
5. Pictures in the blocks "What We Bake" should be animated on hover

**Review by etojeDenys — CHANGES_REQUESTED** [review]
1. still not fixed 
image
image



2. add hovers to these links
image
image

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
1. Add transition for hover effects everywhere
image

2. These icons should lead to the relevant social networks, also add `cursor: pointer` on this icons
image

**Review by anastasiia-tilikina — CHANGES_REQUESTED** [review]
You should add transition on button by default not on hover now it works wrong.
image

these elements should be links and lead to social media opened in a new tab. But now they still aren't

**Review by VitaliyBodnar — CHANGES_REQUESTED** [review]
- image animation is wrong 
- transition should be for in and out (current you have only in)

https://github.com/mate-academy/layout_creativeBakery/assets/64746943/fdde144b-5f86-49d9-90b0-1ed9cff6eb12

- something wrong with page scrolling 

https://github.com/mate-academy/layout_creativeBakery/assets/64746943/654cb1e8-64bf-4aa2-961b-dc95bec5d767

**Review by lerastarynets — CHANGES_REQUESTED** [review]
Pls watch the video review [via the link](https://www.awesomescreenshot.com/video/21426293?key=1243f6457a9a6cdda723cf81eae0450b) :)

**Review by anastasiiavorobiova — APPROVED** [review]
Wonderful work!

**Pull request closed without merging**
