### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by tndeineka**
[DEMO LINK](https://tndeineka.github.io/layout_creativeBakery/)

### CODE REVIEW

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
Good job.
Needs some improvements.
- content should be centered by page horizontally.
chrome-capture-2023-12-5 (1)
Screenshot from 2023-12-05 15-02-17
- on some width when on edge between tablet and mobile layout exists some overlapping. See screenshots and check other sections.
Screenshot from 2023-12-05 14-58-42
- on hover icon becomes invisible. check different states for button on design.
design:
Screenshot from 2023-12-05 15-08-59
actual:
chrome-capture-2023-12-5 (2)

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
Nice improvements.
Looks much better but found a few mismatches with design.
- spaces between cards 
actual:
actual-1
design:
design-1
- space betwieen image and text
actual:
actual-2
design:
design-2

- on mobile view each block should have same width
actual:
actual-3
design:
design-3

**Review by Viktor-Kost — CHANGES_REQUESTED** [review]
Nice!

To improve:
1. To avoid this behavior you need to add some padding to a card

https://github.com/mate-academy/layout_creativeBakery/assets/117587463/c027174b-1180-45b9-a46d-5fef77288206


2. Button doesn't have a background
Screenshot 2023-12-14 at 14 06 28

3. not interactive elements (no needs to add hover effect)
Screenshot 2023-12-14 at 14 08 42

4. social network links should lead to social networks (open in a new tab)
5. don't change button color after click
https://github.com/mate-academy/layout_creativeBakery/assets/117587463/5cfe69d6-14c1-49fb-8ea0-07b8c7d5f0ca

7. The “learn more” button leads to the “About us” block
8. Buttons "order" lead to the contact in footer
9. make menu opening a little bit faster. It shouldn't be a 2 seconds
10. cards haven't overlap each other

https://github.com/mate-academy/layout_creativeBakery/assets/117587463/2918f90b-bc5a-4e0d-bd76-2b2299a0d860

11. cards should be the same width (all available)
Screenshot 2023-12-14 at 14 16 15

**Review by maxim2310 — APPROVED** [review]
Good work, but lets make some improvement 

1. need to add transition on all animations and check why near link is jumping on hover 
image
2.need to centered 
image
3. also links jumping 
image

**Pull request closed without merging**
