### PR TITLE
creative bakery done

### PR DESCRIPTION
**Pull request by Alessandranitti15**
[DEMO LINK](https://Alessandranitti15.github.io/layout_creativeBakery/)

### CODE REVIEW

**Review by polosanya — CHANGES_REQUESTED** [review]
Keep up the good work! Here some comments that would be great to fix:
1. It seems like your header has moved somewhere. 
Please try to fix it.
Currently, it looks like that:
image
2. There should be a [cursor pointer](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) for a button. Also, it should do something and not completely change the color on click. Focused on design probably means [active](https://developer.mozilla.org/en-US/docs/Web/CSS/:active) for the button. 
bakery-button
3. Try to center the content and don't limit its width. Also, please add some hover effect to photos.
image
4. These buttons should do something. For now, there is an error on click.
image
image
5. Add hover effect to all the links and icons
image
6. Make the email clickable. 
https://www.tutorialspoint.com/html/html_email_links.htm
image

**Review by polosanya — CHANGES_REQUESTED** [review]
Great! Almost done! Some more comments that would be great to fix:
1. Maybe let's just change the color on hover? Changing the text case looks a bit strange. Same with links in footer
hover
2. Would be great for phone icon to be a link to the number with the ability to call. Also try to center the text and icon
image
3. Your content is still not properly centred horizontally
image
4. Center the text and icon in the button
image
5. Add some hover effects to these icons. Also, the links should be opened in a new tab.
And try to remove those small blue lines) They are absent on the design
image

**Review by polosanya — CHANGES_REQUESTED** [review]
Demo link is not working(
image
Make sure that you've deployed the changes
Check yourself with the guideline:
https://mate-academy.github.io/layout_task-guideline/

**Comment by Alessandranitti15** [comment]
> Demo link is not working( image Make sure that you've deployed the changes Check yourself with the guideline: https://mate-academy.github.io/layout_task-guideline/

hm weird, to me work, but I'll try to do as you say

**Review by jstmpelowycz — CHANGES_REQUESTED** [review]
- scrolling is not disabled when the menu is opened
- let's make it not that scaled, it overlaps the text coming after it (screenshot 1)
- let's not make words uppercased on hover + add a transition for smooth effect (screenshot 2)
Screenshot 2022-12-06 at 16 38 27
Screenshot 2022-12-06 at 16 46 59

**Review by polosanya — CHANGES_REQUESTED** [review]
Great! Looks really cool. Let's make your page responsive for all screens and devices.
Don't forget to check how it looks on screens with different sizes using DevTools
1. This part doesn't match the design. Pay attention to "Contact us" button
image
image
2. On large screens user can notice the beginning of the next section. Let's try to fix this by making it occupy the entire height of the screen.
image
3. Btw, the button should be placed near the cookie, not under it. And the color doesn't match the design
image
4. Awesome 🔥 
hover-cool
5. Try to centre the content for mobile phones
image

**Review by jstmpelowycz — APPROVED** [review]
nice job!

PS: it still would be much better to have a sense of consistency throughout the landing – hover effects should be of the same kind – text getting upper-cased + no smooth transition – look weird as of UI (my POV)
Screenshot 2022-12-19 at 17 56 31

**Pull request closed without merging**
