### PR TITLE
bakerlab

### PR DESCRIPTION
**Pull request by d-beschastnyi**
[DEMO LINK](https://d-beschastnyi.github.io/layout_creativeBakery/)

### CODE REVIEW

**Review by qoa11a — CHANGES_REQUESTED** [review]
image
Something went wrong. Please fix this. If you need help ask in fe_chat.

**Review by Bohdan-Maksymiuk — CHANGES_REQUESTED** [review]
> Add a smooth scroll for the whole page (scroll-behavior: smooth;)
it doesn't work


https://user-images.githubusercontent.com/94289038/211302253-59d491b2-9a0f-4ced-bab7-817e2ccda57a.mov

* add some hover effects on interactive elements



https://user-images.githubusercontent.com/94289038/211302427-712f85d0-c529-4c6e-a3b0-02cd06fa4c53.mov

* disable scroll at menu

**Review by DarkMistyRoom — CHANGES_REQUESTED** [review]
- check indents between these links on desktop
image

- it looks like the first screen should fit the button completely or it should be lower
image

- add hover effects to all links and apply a transition to them

**Review by Anastasiia-Svintsova — CHANGES_REQUESTED** [review]
- Doesn't match the design. Check the title width
image
- Remove the shadow from the logo, it doesn't match the design.
image
- Check the padding on the 1200px screen, please. 
image
image

- Same here. Check the Figma one more time 
image

**Pull request closed without merging**
